c_stdlib_version:              # [osx and x86_64]
  - 10.15                      # [osx and x86_64]

# We want to build gz-sim-yarp-plugins for Gazebo Harmonic (gz-sim8), Gazebo Ionic (gz-sim9) and Gazebo Jetty (gz-sim10)
GZ_DISTRO_VARIANT:
  - "harmonic"
  - "ionic"
  - "jetty"
